### ISSUE TITLE
[BUG] - After install not showing all list command

### ISSUE THREAD

**Issue by agungsugiarto** [paulbalandan/liaison-revision#1]
After install all command `php spark` is blank
CodeIgniter v4.0.4
PHP v7.3.17
![image](https://user-images.githubusercontent.com/10989147/100302469-f8446d80-2fcc-11eb-91c0-ffaa8473e9ac.png)

**Comment by paulbalandan** [comment]
Please note that you cannot use v4.0.4 for this library to work. As its code is still based on the unreleased version, you need to update your CI4 version to `dev-develop`.

Basing on your terminal output, it seems you are using the released v4.0.4.

**Comment by agungsugiarto** [comment]
Thank u @paulbalandan, now its clear for me.
